###############################################################################
# MedFabric
# Enterprise Healthcare Data & AI Platform
#
# File:
#     src/data_generation/build_raw_data.py
#
# Purpose:
#     Orchestrates the complete Raw layer data generation pipeline.
#
# Business Context:
#     The Raw layer is the foundational data platform layer. It contains
#     synthetic healthcare datasets generated by the MedFabric Synthetic Data
#     Engine.
#
# Inputs:
#     config/data_generation/generation.yaml
#     config/data_generation/*.yaml
#     reference/*/
#
# Outputs:
#     data/raw/*.parquet
#     logs/pipeline/
#
# Run:
#     python -m src.data_generation.build_raw_data
#
###############################################################################

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Tuple

import pandas as pd

from src.common.exception_manager import PipelineError
from src.common.pipeline_context import create_pipeline_context
from src.data_generation.generators.member_generator import run_member_generation
from src.data_generation.generators.organization_generator import run_organization_generation
from src.data_generation.generators.provider_generator import run_provider_generation
from src.data_generation.generators.facility_generator import run_facility_generation
from src.data_generation.generators.enrollment_generator import run_enrollment_generation
from src.data_generation.generators.sdoh_generator import run_sdoh_generation


MODULE_NAME = "medfabric.data_generation.orchestrator"
STEP_NAME = "Raw Layer Data Generation Pipeline"


###############################################################################
# Execution Tracking
###############################################################################

class DatasetExecutionTracker:
    """
    Track execution metrics for one generated dataset.
    """

    def __init__(self, dataset_name: str, generator_name: str):
        self.dataset_name = dataset_name
        self.generator_name = generator_name
        self.start_time: datetime = datetime.now()
        self.end_time: datetime | None = None
        self.row_count: int = 0
        self.column_count: int = 0
        self.success: bool = False
        self.error_message: str | None = None

    def complete(self, dataframe: pd.DataFrame) -> None:
        """
        Mark execution as complete using a generated dataframe.
        """

        self.end_time = datetime.now()
        self.row_count = len(dataframe)
        self.column_count = len(dataframe.columns)
        self.success = True

    def failed(self, error: Exception) -> None:
        """
        Mark execution as failed.
        """

        self.end_time = datetime.now()
        self.success = False
        self.error_message = str(error)

    def duration_seconds(self) -> float:
        """
        Return execution duration in seconds.
        """

        if self.end_time is None:
            return 0.0

        return (self.end_time - self.start_time).total_seconds()

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert tracker to dictionary.
        """

        return {
            "dataset_name": self.dataset_name,
            "generator_name": self.generator_name,
            "start_time": self.start_time.isoformat(),
            "end_time": self.end_time.isoformat() if self.end_time else None,
            "duration_seconds": self.duration_seconds(),
            "row_count": self.row_count,
            "column_count": self.column_count,
            "success": self.success,
            "error_message": self.error_message,
        }


###############################################################################
# Phase 1: Foundational Entities
###############################################################################

def execute_member_generation(context, trackers: List[DatasetExecutionTracker]) -> pd.DataFrame:
    """
    Execute Member dataset generation.
    """

    logger = context.get_logger(MODULE_NAME)
    tracker = DatasetExecutionTracker("raw.members", "member_generator")
    trackers.append(tracker)

    try:
        logger.info("Starting Member generation...")
        dataframe = run_member_generation(context)
        tracker.complete(dataframe)
        logger.info("Member generation completed. Rows: %s", tracker.row_count)
        return dataframe

    except Exception as error:
        tracker.failed(error)
        logger.exception("Member generation failed.")
        raise


def execute_organization_generation(context, trackers: List[DatasetExecutionTracker]) -> pd.DataFrame:
    """
    Execute Organization dataset generation.
    """

    logger = context.get_logger(MODULE_NAME)
    tracker = DatasetExecutionTracker("raw.organizations", "organization_generator")
    trackers.append(tracker)

    try:
        logger.info("Starting Organization generation...")
        dataframe = run_organization_generation(context)
        tracker.complete(dataframe)
        logger.info("Organization generation completed. Rows: %s", tracker.row_count)
        return dataframe

    except Exception as error:
        tracker.failed(error)
        logger.exception("Organization generation failed.")
        raise


def execute_facility_generation(context, trackers: List[DatasetExecutionTracker]) -> pd.DataFrame:
    """
    Execute Facility dataset generation.
    """

    logger = context.get_logger(MODULE_NAME)
    tracker = DatasetExecutionTracker("raw.facilities", "facility_generator")
    trackers.append(tracker)

    try:
        logger.info("Starting Facility generation...")
        dataframe = run_facility_generation(context)
        tracker.complete(dataframe)
        logger.info("Facility generation completed. Rows: %s", tracker.row_count)
        return dataframe

    except Exception as error:
        tracker.failed(error)
        logger.exception("Facility generation failed.")
        raise


def execute_provider_generation(context, trackers: List[DatasetExecutionTracker]) -> pd.DataFrame:
    """
    Execute Provider dataset generation.
    """

    logger = context.get_logger(MODULE_NAME)
    tracker = DatasetExecutionTracker("raw.providers", "provider_generator")
    trackers.append(tracker)

    try:
        logger.info("Starting Provider generation...")
        dataframe = run_provider_generation(context)
        tracker.complete(dataframe)
        logger.info("Provider generation completed. Rows: %s", tracker.row_count)
        return dataframe

    except Exception as error:
        tracker.failed(error)
        logger.exception("Provider generation failed.")
        raise


###############################################################################
# Phase 2: Relationship Entities
###############################################################################

def execute_enrollment_generation(
    context,
    trackers: List[DatasetExecutionTracker],
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Execute Enrollment and Member Month generation.

    Important:
        run_enrollment_generation(context) returns two dataframes:

            1. enrollment_df
            2. member_months_df

        The previous orchestrator treated that tuple as one dataframe, which
        caused:

            AttributeError: 'tuple' object has no attribute 'columns'

        This function now tracks both generated datasets separately.
    """

    logger = context.get_logger(MODULE_NAME)

    enrollment_tracker = DatasetExecutionTracker(
        "raw.enrollment",
        "enrollment_generator",
    )
    member_months_tracker = DatasetExecutionTracker(
        "raw.member_months",
        "enrollment_generator",
    )

    trackers.append(enrollment_tracker)
    trackers.append(member_months_tracker)

    try:
        logger.info("Starting Enrollment and Member Month generation...")

        result = run_enrollment_generation(context)

        if not isinstance(result, tuple) or len(result) != 2:
            raise PipelineError(
                "run_enrollment_generation must return "
                "(enrollment_df, member_months_df)."
            )

        enrollment_df, member_months_df = result

        enrollment_tracker.complete(enrollment_df)
        member_months_tracker.complete(member_months_df)

        logger.info(
            "Enrollment generation completed. Rows: %s",
            enrollment_tracker.row_count,
        )
        logger.info(
            "Member Month generation completed. Rows: %s",
            member_months_tracker.row_count,
        )

        return enrollment_df, member_months_df

    except Exception as error:
        enrollment_tracker.failed(error)
        member_months_tracker.failed(error)
        logger.exception("Enrollment / Member Month generation failed.")
        raise


def execute_sdoh_generation(context, trackers: List[DatasetExecutionTracker]) -> pd.DataFrame:
    """
    Execute SDOH dataset generation.
    """

    logger = context.get_logger(MODULE_NAME)
    tracker = DatasetExecutionTracker("raw.sdoh", "sdoh_generator")
    trackers.append(tracker)

    try:
        logger.info("Starting SDOH generation...")
        dataframe = run_sdoh_generation(context)
        tracker.complete(dataframe)
        logger.info("SDOH generation completed. Rows: %s", tracker.row_count)
        return dataframe

    except Exception as error:
        tracker.failed(error)
        logger.exception("SDOH generation failed.")
        raise


###############################################################################
# Execution Summary
###############################################################################

def generate_execution_summary(
    context,
    trackers: List[DatasetExecutionTracker],
    pipeline_start_time: datetime,
) -> Dict[str, Any]:
    """
    Generate execution summary for the raw data generation pipeline.
    """

    logger = context.get_logger(MODULE_NAME)

    pipeline_end_time = datetime.now()
    pipeline_duration = (pipeline_end_time - pipeline_start_time).total_seconds()

    successful_datasets = [tracker for tracker in trackers if tracker.success]
    failed_datasets = [tracker for tracker in trackers if not tracker.success]

    total_rows = sum(tracker.row_count for tracker in successful_datasets)
    total_columns = sum(tracker.column_count for tracker in successful_datasets)

    summary: Dict[str, Any] = {
        "pipeline_name": "Raw Layer Data Generation",
        "execution_date": pipeline_start_time.isoformat(),
        "pipeline_duration_seconds": pipeline_duration,
        "total_datasets_attempted": len(trackers),
        "successful_datasets": len(successful_datasets),
        "failed_datasets": len(failed_datasets),
        "total_rows_generated": total_rows,
        "total_columns_generated": total_columns,
        "run_id": context.run_id,
        "pipeline_context": context.to_dict(),
        "dataset_executions": [tracker.to_dict() for tracker in trackers],
    }

    logger.info("=" * 80)
    logger.info("RAW LAYER EXECUTION SUMMARY")
    logger.info("=" * 80)
    logger.info("Pipeline Duration: %.2f seconds", pipeline_duration)
    logger.info("Successful Datasets: %s", len(successful_datasets))
    logger.info("Failed Datasets: %s", len(failed_datasets))
    logger.info("Total Rows Generated: %s", total_rows)
    logger.info("Total Columns Generated: %s", total_columns)

    for dataset_tracker in successful_datasets:
        logger.info(
            "  ✓ %s: %s rows, %s columns (%.2f seconds)",
            dataset_tracker.dataset_name,
            dataset_tracker.row_count,
            dataset_tracker.column_count,
            dataset_tracker.duration_seconds(),
        )

    for dataset_tracker in failed_datasets:
        logger.error(
            "  ✗ %s: FAILED - %s",
            dataset_tracker.dataset_name,
            dataset_tracker.error_message,
        )

    logger.info("=" * 80)

    return summary


###############################################################################
# Orchestration
###############################################################################

def run_raw_data_generation_pipeline(context) -> Dict[str, Any]:
    """
    Execute the complete Raw layer data generation pipeline.
    """

    logger = context.get_logger(MODULE_NAME)
    pipeline_start_time = datetime.now()
    trackers: List[DatasetExecutionTracker] = []

    logger.info("Starting Raw Layer Data Generation Pipeline")
    logger.info("Pipeline Run ID: %s", context.run_id)

    try:
        logger.info("=" * 80)
        logger.info("PHASE 1: Foundational Entities")
        logger.info("=" * 80)

        execute_member_generation(context, trackers)
        execute_organization_generation(context, trackers)
        execute_facility_generation(context, trackers)
        execute_provider_generation(context, trackers)

        logger.info("=" * 80)
        logger.info("PHASE 2: Relationship Entities")
        logger.info("=" * 80)

        execute_enrollment_generation(context, trackers)
        execute_sdoh_generation(context, trackers)

        logger.info("=" * 80)
        logger.info("PHASE 3: Event Entities")
        logger.info("=" * 80)
        logger.info("Event generators are not currently wired into this orchestrator.")

        logger.info("=" * 80)
        logger.info("GENERATING EXECUTION SUMMARY")
        logger.info("=" * 80)

        return generate_execution_summary(context, trackers, pipeline_start_time)

    except Exception as error:
        logger.exception("Raw data generation pipeline failed.")
        raise PipelineError("Raw data generation pipeline failed.") from error


###############################################################################
# CLI Entry Point
###############################################################################

def main() -> None:
    """
    Command-line entry point for Raw layer data generation.
    """

    context = create_pipeline_context()
    logger = context.get_logger(MODULE_NAME)

    try:
        context.logging.start_step(STEP_NAME)

        summary = run_raw_data_generation_pipeline(context)

        context.logging.end_step(STEP_NAME)

        logger.info("Raw layer data generation pipeline completed successfully.")

        print("\n" + "=" * 80)
        print("RAW LAYER DATA GENERATION COMPLETED")
        print("=" * 80)
        print(f"Pipeline Duration: {summary['pipeline_duration_seconds']:.2f} seconds")
        print(f"Successful Datasets: {summary['successful_datasets']}")
        print(f"Failed Datasets: {summary['failed_datasets']}")
        print(f"Total Rows Generated: {summary['total_rows_generated']}")
        print("=" * 80 + "\n")

    except Exception as error:
        context.logging.log_exception(error, "Raw data generation pipeline failed.")
        logger.exception("Raw data generation pipeline failed.")
        raise PipelineError("Raw data generation pipeline failed.") from error

    finally:
        context.logging.close()


if __name__ == "__main__":
    main()