###############################################################################
# MedFabric
# Enterprise Healthcare Data & AI Platform
#
# File:
#     src/data_generation/build_raw_data.py
#
# Purpose:
#     Orchestrates the complete Raw layer data generation pipeline.
#
# Business Context:
#     The Raw layer is the foundational data platform layer. It contains
#     synthetic healthcare datasets generated by the MedFabric Synthetic Data
#     Engine.
#
#     This orchestrator is the single entry point that coordinates generation
#     of all 10 raw datasets in proper dependency order, validates outputs,
#     and generates comprehensive execution reporting.
#
# Inputs:
#     config/data_generation/generation.yaml
#     config/data_generation/*.yaml (per-generator configs)
#     reference/*/
#
# Outputs:
#     data/raw/*.parquet (10 datasets)
#     data/metadata/* (metadata for all datasets)
#     logs/pipeline/ (execution logs)
#
# Generated Datasets:
#     1. members.parquet
#     2. organizations.parquet
#     3. providers.parquet
#     4. facilities.parquet
#     5. enrollment.parquet
#     6. member_months.parquet
#     7. encounters.parquet
#     8. claim_headers.parquet
#     9. claim_lines.parquet
#     10. pharmacy.parquet
#     11. laboratory.parquet
#     12. sdoh.parquet
#
# Dependencies:
#     src.common.pipeline_context.create_pipeline_context
#     src.common.exception_manager.PipelineError
#     src.data_generation.generators.member_generator
#     src.data_generation.generators.organization_generator
#     src.data_generation.generators.provider_generator
#     src.data_generation.generators.facility_generator
#     src.data_generation.generators.enrollment_generator
#     src.data_generation.generators.member_months_generator
#     src.data_generation.generators.encounter_generator
#     src.data_generation.generators.claims_generator
#     src.data_generation.generators.pharmacy_generator
#     src.data_generation.generators.laboratory_generator
#     src.data_generation.generators.sdoh_generator
#
# Architectural Rules:
#     1. Use PipelineContext for all generator invocations.
#     2. Do not duplicate configuration loading. Pass context to generators.
#     3. Do not call context.logging.close() until all generators complete.
#     4. Track execution time for each generator and total pipeline time.
#     5. Validate all outputs before proceeding to next generator.
#     6. Generate comprehensive execution summary and lineage.
#     7. Propagate exceptions from generators without swallowing errors.
#
# Execution Order:
#     Phase 1 (Foundational Entities):
#         1. Members          (base person entity)
#         2. Organizations    (base enterprise entity)
#         3. Facilities       (base location entity)
#         4. Providers        (depends on Organizations)
#
#     Phase 2 (Relationships):
#         5. Enrollment       (depends on Members)
#         6. Member Months    (depends on Members, Enrollment)
#         7. SDOH            (depends on Members)
#
#     Phase 3 (Events):
#         8. Encounters       (depends on Facilities, Providers)
#         9. Claims           (depends on Encounters, Members)
#         10. Pharmacy        (depends on Members)
#         11. Laboratory      (depends on Members)
#
# Run Command:
#     python -m src.data_generation.build_raw_data
#
# Expected Output:
#     All 12 Raw layer datasets, metadata, and execution report.
#
###############################################################################

from __future__ import annotations

import time
from datetime import datetime
from typing import Any, Dict, List, Tuple

import pandas as pd

from src.common.exception_manager import PipelineError
from src.common.pipeline_context import create_pipeline_context
from src.data_generation.generators.member_generator import run_member_generation
from src.data_generation.generators.organization_generator import (
    run_organization_generation,
)
from src.data_generation.generators.provider_generator import run_provider_generation
from src.data_generation.generators.facility_generator import run_facility_generation
from src.data_generation.generators.enrollment_generator import (
    run_enrollment_generation,
)
from src.data_generation.generators.sdoh_generator import run_sdoh_generation


MODULE_NAME = "medfabric.data_generation.orchestrator"
STEP_NAME = "Raw Layer Data Generation Pipeline"


###############################################################################
# EXECUTION TRACKING
###############################################################################


class DatasetExecutionTracker:
    """
    Track execution metrics for each generated dataset.

    Attributes:
        dataset_name: Logical dataset name
        generator_name: Generator module name
        start_time: Execution start timestamp
        end_time: Execution end timestamp
        row_count: Generated row count
        column_count: Generated column count
        success: Whether generation succeeded
        error_message: Error message if failed
    """

    def __init__(self, dataset_name: str, generator_name: str):
        self.dataset_name = dataset_name
        self.generator_name = generator_name
        self.start_time: datetime = datetime.now()
        self.end_time: datetime | None = None
        self.row_count: int = 0
        self.column_count: int = 0
        self.success: bool = False
        self.error_message: str | None = None

    def complete(self, dataframe: pd.DataFrame) -> None:
        """Mark execution as complete with row/column counts."""
        self.end_time = datetime.now()
        self.row_count = len(dataframe)
        self.column_count = len(dataframe.columns)
        self.success = True

    def failed(self, error: Exception) -> None:
        """Mark execution as failed with error message."""
        self.end_time = datetime.now()
        self.success = False
        self.error_message = str(error)

    def duration_seconds(self) -> float:
        """Return execution duration in seconds."""
        if self.end_time is None:
            return 0.0
        return (self.end_time - self.start_time).total_seconds()

    def to_dict(self) -> Dict[str, Any]:
        """Convert tracker to dictionary."""
        return {
            "dataset_name": self.dataset_name,
            "generator_name": self.generator_name,
            "start_time": self.start_time.isoformat(),
            "end_time": self.end_time.isoformat() if self.end_time else None,
            "duration_seconds": self.duration_seconds(),
            "row_count": self.row_count,
            "column_count": self.column_count,
            "success": self.success,
            "error_message": self.error_message,
        }


###############################################################################
# PHASE 1: FOUNDATIONAL ENTITIES
###############################################################################


def execute_member_generation(
    context,
    trackers: List[DatasetExecutionTracker],
) -> pd.DataFrame:
    """
    Execute Member dataset generation (foundational entity).

    Parameters
    ----------
    context:
        Active MedFabric PipelineContext.

    trackers:
        Execution tracking list.

    Returns
    -------
    pandas.DataFrame
        Generated Member dataset.
    """
    logger = context.get_logger(MODULE_NAME)
    tracker = DatasetExecutionTracker("raw.members", "member_generator")
    trackers.append(tracker)

    try:
        logger.info("Starting Member generation...")
        dataframe = run_member_generation(context)
        tracker.complete(dataframe)
        logger.info("Member generation completed. Rows: %s", tracker.row_count)
        return dataframe

    except Exception as error:
        tracker.failed(error)
        logger.exception("Member generation failed.")
        raise


def execute_organization_generation(
    context,
    trackers: List[DatasetExecutionTracker],
) -> pd.DataFrame:
    """
    Execute Organization dataset generation (foundational entity).

    Parameters
    ----------
    context:
        Active MedFabric PipelineContext.

    trackers:
        Execution tracking list.

    Returns
    -------
    pandas.DataFrame
        Generated Organization dataset.
    """
    logger = context.get_logger(MODULE_NAME)
    tracker = DatasetExecutionTracker("raw.organizations", "organization_generator")
    trackers.append(tracker)

    try:
        logger.info("Starting Organization generation...")
        dataframe = run_organization_generation(context)
        tracker.complete(dataframe)
        logger.info("Organization generation completed. Rows: %s", tracker.row_count)
        return dataframe

    except Exception as error:
        tracker.failed(error)
        logger.exception("Organization generation failed.")
        raise


def execute_facility_generation(
    context,
    trackers: List[DatasetExecutionTracker],
) -> pd.DataFrame:
    """
    Execute Facility dataset generation (foundational entity).

    Parameters
    ----------
    context:
        Active MedFabric PipelineContext.

    trackers:
        Execution tracking list.

    Returns
    -------
    pandas.DataFrame
        Generated Facility dataset.
    """
    logger = context.get_logger(MODULE_NAME)
    tracker = DatasetExecutionTracker("raw.facilities", "facility_generator")
    trackers.append(tracker)

    try:
        logger.info("Starting Facility generation...")
        dataframe = run_facility_generation(context)
        tracker.complete(dataframe)
        logger.info("Facility generation completed. Rows: %s", tracker.row_count)
        return dataframe

    except Exception as error:
        tracker.failed(error)
        logger.exception("Facility generation failed.")
        raise


def execute_provider_generation(
    context,
    trackers: List[DatasetExecutionTracker],
) -> pd.DataFrame:
    """
    Execute Provider dataset generation (depends on Organizations).

    Parameters
    ----------
    context:
        Active MedFabric PipelineContext.

    trackers:
        Execution tracking list.

    Returns
    -------
    pandas.DataFrame
        Generated Provider dataset.
    """
    logger = context.get_logger(MODULE_NAME)
    tracker = DatasetExecutionTracker("raw.providers", "provider_generator")
    trackers.append(tracker)

    try:
        logger.info("Starting Provider generation...")
        dataframe = run_provider_generation(context)
        tracker.complete(dataframe)
        logger.info("Provider generation completed. Rows: %s", tracker.row_count)
        return dataframe

    except Exception as error:
        tracker.failed(error)
        logger.exception("Provider generation failed.")
        raise


###############################################################################
# PHASE 2: RELATIONSHIP ENTITIES
###############################################################################


def execute_enrollment_generation(
    context,
    trackers: List[DatasetExecutionTracker],
) -> pd.DataFrame:
    """
    Execute Enrollment dataset generation (depends on Members).

    Parameters
    ----------
    context:
        Active MedFabric PipelineContext.

    trackers:
        Execution tracking list.

    Returns
    -------
    pandas.DataFrame
        Generated Enrollment dataset.
    """
    logger = context.get_logger(MODULE_NAME)
    tracker = DatasetExecutionTracker("raw.enrollment", "enrollment_generator")
    trackers.append(tracker)

    try:
        logger.info("Starting Enrollment generation...")
        dataframe = run_enrollment_generation(context)
        tracker.complete(dataframe)
        logger.info("Enrollment generation completed. Rows: %s", tracker.row_count)
        return dataframe

    except Exception as error:
        tracker.failed(error)
        logger.exception("Enrollment generation failed.")
        raise


def execute_sdoh_generation(
    context,
    trackers: List[DatasetExecutionTracker],
) -> pd.DataFrame:
    """
    Execute SDOH dataset generation (depends on Members).

    Parameters
    ----------
    context:
        Active MedFabric PipelineContext.

    trackers:
        Execution tracking list.

    Returns
    -------
    pandas.DataFrame
        Generated SDOH dataset.
    """
    logger = context.get_logger(MODULE_NAME)
    tracker = DatasetExecutionTracker("raw.sdoh", "sdoh_generator")
    trackers.append(tracker)

    try:
        logger.info("Starting SDOH generation...")
        dataframe = run_sdoh_generation(context)
        tracker.complete(dataframe)
        logger.info("SDOH generation completed. Rows: %s", tracker.row_count)
        return dataframe

    except Exception as error:
        tracker.failed(error)
        logger.exception("SDOH generation failed.")
        raise


###############################################################################
# EXECUTION SUMMARY
###############################################################################


def generate_execution_summary(
    context,
    trackers: List[DatasetExecutionTracker],
    pipeline_start_time: datetime,
) -> Dict[str, Any]:
    """
    Generate comprehensive execution summary and report.

    Parameters
    ----------
    context:
        Active MedFabric PipelineContext.

    trackers:
        Execution tracking list for all datasets.

    pipeline_start_time:
        Pipeline start timestamp.

    Returns
    -------
    dict
        Execution summary.
    """
    logger = context.get_logger(MODULE_NAME)

    pipeline_end_time = datetime.now()
    pipeline_duration = (pipeline_end_time - pipeline_start_time).total_seconds()

    successful_datasets = [t for t in trackers if t.success]
    failed_datasets = [t for t in trackers if not t.success]

    total_rows = sum(t.row_count for t in successful_datasets)
    total_columns = sum(t.column_count for t in successful_datasets)

    summary: Dict[str, Any] = {
        "pipeline_name": "Raw Layer Data Generation",
        "execution_date": pipeline_start_time.isoformat(),
        "pipeline_duration_seconds": pipeline_duration,
        "total_datasets_attempted": len(trackers),
        "successful_datasets": len(successful_datasets),
        "failed_datasets": len(failed_datasets),
        "total_rows_generated": total_rows,
        "total_columns_generated": total_columns,
        "run_id": context.run_id,
        "pipeline_context": context.to_dict(),
        "dataset_executions": [t.to_dict() for t in trackers],
    }

    logger.info("=" * 80)
    logger.info("RAW LAYER EXECUTION SUMMARY")
    logger.info("=" * 80)
    logger.info("Pipeline Duration: %.2f seconds", pipeline_duration)
    logger.info("Successful Datasets: %s", len(successful_datasets))
    logger.info("Failed Datasets: %s", len(failed_datasets))
    logger.info("Total Rows Generated: %s", total_rows)
    logger.info("Total Columns Generated: %s", total_columns)

    for dataset_tracker in successful_datasets:
        logger.info(
            "  ✓ %s: %s rows, %s columns (%.2f seconds)",
            dataset_tracker.dataset_name,
            dataset_tracker.row_count,
            dataset_tracker.column_count,
            dataset_tracker.duration_seconds(),
        )

    for dataset_tracker in failed_datasets:
        logger.error(
            "  ✗ %s: FAILED - %s",
            dataset_tracker.dataset_name,
            dataset_tracker.error_message,
        )

    logger.info("=" * 80)

    return summary


###############################################################################
# ORCHESTRATION
###############################################################################


def run_raw_data_generation_pipeline(context) -> Dict[str, Any]:
    """
    Execute the complete Raw layer data generation pipeline.

    This is the master orchestrator that coordinates generation of all Raw
    layer datasets in proper dependency order.

    Parameters
    ----------
    context:
        Active MedFabric PipelineContext.

    Returns
    -------
    dict
        Execution summary with metrics for all datasets.

    Raises
    ------
    PipelineError
        Raised when any dataset generation fails and stop_on_error is enabled.
    """
    logger = context.get_logger(MODULE_NAME)
    pipeline_start_time = datetime.now()
    trackers: List[DatasetExecutionTracker] = []

    logger.info("Starting Raw Layer Data Generation Pipeline")
    logger.info("Pipeline Run ID: %s", context.run_id)

    try:
        # Phase 1: Foundational Entities
        logger.info("=" * 80)
        logger.info("PHASE 1: Foundational Entities")
        logger.info("=" * 80)

        execute_member_generation(context, trackers)
        execute_organization_generation(context, trackers)
        execute_facility_generation(context, trackers)
        execute_provider_generation(context, trackers)

        # Phase 2: Relationship Entities
        logger.info("=" * 80)
        logger.info("PHASE 2: Relationship Entities")
        logger.info("=" * 80)

        execute_enrollment_generation(context, trackers)
        execute_sdoh_generation(context, trackers)

        # Phase 3: Event Entities
        # (Encounter, Claims, Pharmacy, Laboratory generators will be added)
        logger.info("=" * 80)
        logger.info("PHASE 3: Event Entities")
        logger.info("=" * 80)
        logger.info("(Encounter, Claims, Pharmacy, Laboratory generation)")
        logger.info("(To be implemented by respective generators)")

        # Generate execution summary
        logger.info("=" * 80)
        logger.info("GENERATING EXECUTION SUMMARY")
        logger.info("=" * 80)

        summary = generate_execution_summary(context, trackers, pipeline_start_time)

        return summary

    except Exception as error:
        logger.exception("Raw data generation pipeline failed.")
        raise PipelineError("Raw data generation pipeline failed.") from error


def main() -> None:
    """
    Main entry point for Raw layer data generation.

    Run Command
    -----------
    python -m src.data_generation.build_raw_data
    """
    context = create_pipeline_context()
    logger = context.get_logger(MODULE_NAME)

    try:
        context.logging.start_step(STEP_NAME)

        summary = run_raw_data_generation_pipeline(context)

        context.logging.end_step(STEP_NAME)

        logger.info("Raw layer data generation pipeline completed successfully.")

        print("\n" + "=" * 80)
        print("RAW LAYER DATA GENERATION COMPLETED")
        print("=" * 80)
        print(f"Pipeline Duration: {summary['pipeline_duration_seconds']:.2f} seconds")
        print(f"Successful Datasets: {summary['successful_datasets']}")
        print(f"Failed Datasets: {summary['failed_datasets']}")
        print(f"Total Rows Generated: {summary['total_rows_generated']}")
        print("=" * 80 + "\n")

    except Exception as error:
        context.logging.log_exception(error, "Raw data generation pipeline failed.")
        logger.exception("Raw data generation pipeline failed.")
        raise PipelineError("Raw data generation pipeline failed.") from error

    finally:
        context.logging.close()


if __name__ == "__main__":
    main()
