###############################################################################
# MedFabric
# Enterprise Healthcare Data & AI Platform
#
# File:
#     src/semantic_layer/build_semantic_layer.py
#
# Layer:
#     Layer 1G - Semantic Layer
#
# Purpose:
#     Builds the MedFabric Semantic Layer from Feature Store outputs.
#
#     The Semantic Layer converts curated feature-store datasets into
#     business-friendly semantic assets that can be consumed by analytics,
#     reporting, dashboards, notebooks, governance workflows, and future AI
#     applications.
#
# Business Context:
#     Healthcare data platforms often contain technically correct datasets that
#     are difficult for business users to consume directly. The Semantic Layer
#     provides a business-facing interpretation of platform data by organizing
#     feature-store outputs into:
#
#         - Semantic dimensions
#         - Semantic metrics
#         - Semantic business views
#         - Metric definitions
#         - Entity mappings
#         - Validation reports
#         - Metadata catalogs
#         - Audit summaries
#
#     This layer creates a consistent business vocabulary across payer analytics
#     use cases such as:
#
#         - Member 360
#         - Population health analytics
#         - Risk analytics
#         - Utilization analytics
#         - Provider performance analytics
#         - Quality analytics
#         - Care management prioritization
#
# Inputs:
#     Configuration:
#         config/semantic_layer/semantic_layer.yaml
#
#     Expected upstream data:
#         Feature Store datasets generated by Layer 1F.
#
#     The exact input paths, output paths, enabled semantic assets, validation
#     rules, and metric definitions should be controlled by YAML configuration.
#
# Outputs:
#     Depending on configuration, this script can write:
#
#         - Semantic dimensions
#         - Semantic metric tables
#         - Semantic business views
#         - Semantic metadata catalog
#         - Semantic entity mapping catalog
#         - Semantic metric definition catalog
#         - Semantic validation results
#         - Semantic execution summary
#         - Semantic audit records
#
# Repository Pattern:
#     This file follows the established MedFabric repository pattern:
#
#         config/semantic_layer/semantic_layer.yaml
#         src/semantic_layer/build_semantic_layer.py
#         data/semantic_layer/...
#         docs/Semantic_Layer_Architecture.md
#         logs/pipeline/...
#         logs/modules/...
#         logs/audit/...
#         logs/errors/...
#
# Design Principles:
#     - No hardcoded project-specific paths.
#     - Configuration-driven execution.
#     - Defensive validation.
#     - Clear logging.
#     - Repeatable outputs.
#     - Business-friendly metadata.
#     - Full-file readability.
#     - Main block included.
#
# Run:
#     python -m src.semantic_layer.build_semantic_layer
#
###############################################################################

from __future__ import annotations

import json
import logging
import os
import sys
import time
import traceback
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

import pandas as pd
import yaml


###############################################################################
# Constants
###############################################################################

DEFAULT_CONFIG_PATH = "config/semantic_layer/semantic_layer.yaml"

DEFAULT_LAYER_NAME = "Layer 1G - Semantic Layer"

SUPPORTED_FILE_FORMATS = {"parquet", "csv", "json"}

DEFAULT_OUTPUT_FORMAT = "parquet"

AUDIT_STATUS_SUCCESS = "SUCCESS"
AUDIT_STATUS_FAILED = "FAILED"
AUDIT_STATUS_WARNING = "WARNING"
AUDIT_STATUS_SKIPPED = "SKIPPED"


###############################################################################
# Data Classes
###############################################################################

@dataclass
class SemanticLayerRuntime:
    """
    Runtime context for a single Semantic Layer execution.

    This object is passed between functions so that the script does not rely on
    global mutable state for execution metadata.
    """

    run_id: str
    layer_name: str
    project_root: Path
    config_path: Path
    start_time_utc: datetime
    logger: logging.Logger
    config: Dict[str, Any]
    audit_records: List[Dict[str, Any]] = field(default_factory=list)
    validation_records: List[Dict[str, Any]] = field(default_factory=list)
    dataset_records: List[Dict[str, Any]] = field(default_factory=list)
    metric_records: List[Dict[str, Any]] = field(default_factory=list)


@dataclass
class DatasetResult:
    """
    Standardized result for a dataset load or build operation.
    """

    name: str
    status: str
    row_count: int = 0
    column_count: int = 0
    path: Optional[str] = None
    message: Optional[str] = None


###############################################################################
# General Utility Functions
###############################################################################

def utc_now() -> datetime:
    """
    Return the current UTC timestamp.

    Returns:
        datetime:
            Timezone-aware UTC timestamp.
    """

    return datetime.now(timezone.utc)


def generate_run_id() -> str:
    """
    Generate a timestamp-based run identifier.

    Returns:
        str:
            Run ID in YYYYMMDD_HHMMSS format.
    """

    return utc_now().strftime("%Y%m%d_%H%M%S")


def normalize_path(project_root: Path, raw_path: str | Path) -> Path:
    """
    Resolve a configured path relative to the project root.

    Args:
        project_root:
            Root directory of the MedFabric repository.

        raw_path:
            Path from configuration. May be absolute or relative.

    Returns:
        Path:
            Resolved absolute path.
    """

    path = Path(raw_path)

    if path.is_absolute():
        return path

    return project_root / path


def ensure_directory(path: Path) -> None:
    """
    Create a directory if it does not exist.

    Args:
        path:
            Directory path to create.
    """

    path.mkdir(parents=True, exist_ok=True)


def safe_string(value: Any) -> str:
    """
    Convert a value into a safe string.

    Args:
        value:
            Any Python value.

    Returns:
        str:
            String representation.
    """

    if value is None:
        return ""

    return str(value)


def flatten_dict(
    data: Dict[str, Any],
    parent_key: str = "",
    separator: str = ".",
) -> Dict[str, Any]:
    """
    Flatten a nested dictionary for easier metadata reporting.

    Args:
        data:
            Nested dictionary.

        parent_key:
            Prefix used during recursion.

        separator:
            Separator between nested keys.

    Returns:
        Dict[str, Any]:
            Flattened dictionary.
    """

    flattened: Dict[str, Any] = {}

    for key, value in data.items():
        new_key = f"{parent_key}{separator}{key}" if parent_key else str(key)

        if isinstance(value, dict):
            flattened.update(flatten_dict(value, new_key, separator))
        else:
            flattened[new_key] = value

    return flattened


###############################################################################
# Logging
###############################################################################

def configure_logging(project_root: Path, config: Dict[str, Any], run_id: str) -> logging.Logger:
    """
    Configure centralized logging for the Semantic Layer.

    Logging paths are read from configuration when provided. If the configuration
    does not provide logging paths, this function uses the established MedFabric
    logging pattern under logs/modules.

    Args:
        project_root:
            Repository root.

        config:
            Semantic layer configuration dictionary.

        run_id:
            Current run identifier.

    Returns:
        logging.Logger:
            Configured logger.
    """

    logging_config = config.get("logging", {})

    log_level_name = logging_config.get("level", "INFO")
    log_level = getattr(logging, str(log_level_name).upper(), logging.INFO)

    module_log_dir_raw = (
        logging_config.get("module_log_dir")
        or logging_config.get("semantic_layer_log_dir")
        or "logs/modules"
    )

    module_log_dir = normalize_path(project_root, module_log_dir_raw)
    ensure_directory(module_log_dir)

    log_file_name = logging_config.get(
        "log_file_name",
        f"semantic_layer_{run_id}.log",
    )

    log_file_path = module_log_dir / log_file_name

    logger = logging.getLogger("medfabric.semantic_layer")
    logger.setLevel(log_level)
    logger.handlers.clear()
    logger.propagate = False

    formatter = logging.Formatter(
        fmt="[%(asctime)s] [RUN_ID=%(run_id)s] [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    class RunIdFilter(logging.Filter):
        def filter(self, record: logging.LogRecord) -> bool:
            record.run_id = run_id
            return True

    stream_handler = logging.StreamHandler(sys.stdout)
    stream_handler.setLevel(log_level)
    stream_handler.setFormatter(formatter)
    stream_handler.addFilter(RunIdFilter())

    file_handler = logging.FileHandler(log_file_path, encoding="utf-8")
    file_handler.setLevel(log_level)
    file_handler.setFormatter(formatter)
    file_handler.addFilter(RunIdFilter())

    logger.addHandler(stream_handler)
    logger.addHandler(file_handler)

    logger.info("=" * 80)
    logger.info("MedFabric Semantic Layer execution started")
    logger.info("=" * 80)
    logger.info("Run ID: %s", run_id)
    logger.info("Log file: %s", log_file_path)

    return logger


###############################################################################
# Configuration Loading and Validation
###############################################################################

def load_yaml_config(config_path: Path) -> Dict[str, Any]:
    """
    Load YAML configuration.

    Args:
        config_path:
            Path to YAML configuration file.

    Returns:
        Dict[str, Any]:
            Parsed YAML configuration.

    Raises:
        FileNotFoundError:
            If the configuration file does not exist.

        ValueError:
            If the configuration is empty or not a dictionary.
    """

    if not config_path.exists():
        raise FileNotFoundError(f"Configuration file not found: {config_path}")

    with config_path.open("r", encoding="utf-8") as config_file:
        config = yaml.safe_load(config_file)

    if config is None:
        raise ValueError(f"Configuration file is empty: {config_path}")

    if not isinstance(config, dict):
        raise ValueError(
            f"Configuration file must contain a YAML mapping/object: {config_path}"
        )

    return config


def validate_required_config_sections(config: Dict[str, Any]) -> List[str]:
    """
    Validate that the minimum required configuration sections exist.

    Args:
        config:
            Semantic layer configuration.

    Returns:
        List[str]:
            Validation error messages.
    """

    errors: List[str] = []

    required_sections = [
        "semantic_layer",
        "paths",
    ]

    for section in required_sections:
        if section not in config:
            errors.append(f"Missing required configuration section: {section}")

    paths = config.get("paths", {})

    if not isinstance(paths, dict):
        errors.append("Configuration section 'paths' must be a dictionary.")
    else:
        if "inputs" not in paths:
            errors.append("Missing required configuration section: paths.inputs")

        if "outputs" not in paths:
            errors.append("Missing required configuration section: paths.outputs")

    return errors


def validate_config(config: Dict[str, Any]) -> None:
    """
    Validate semantic layer configuration.

    Args:
        config:
            Loaded YAML configuration.

    Raises:
        ValueError:
            If required configuration is missing or invalid.
    """

    errors = validate_required_config_sections(config)

    output_format = (
        config.get("semantic_layer", {})
        .get("output_format", DEFAULT_OUTPUT_FORMAT)
    )

    if output_format not in SUPPORTED_FILE_FORMATS:
        errors.append(
            f"Unsupported output_format '{output_format}'. "
            f"Supported formats: {sorted(SUPPORTED_FILE_FORMATS)}"
        )

    if errors:
        error_message = "\n".join(f"- {error}" for error in errors)
        raise ValueError(f"Semantic layer configuration validation failed:\n{error_message}")


###############################################################################
# Runtime Initialization
###############################################################################

def initialize_runtime(config_path_raw: str = DEFAULT_CONFIG_PATH) -> SemanticLayerRuntime:
    """
    Initialize runtime context.

    Args:
        config_path_raw:
            Path to semantic layer YAML configuration.

    Returns:
        SemanticLayerRuntime:
            Runtime context for the run.
    """

    project_root = Path.cwd()
    config_path = normalize_path(project_root, config_path_raw)
    run_id = generate_run_id()

    config = load_yaml_config(config_path)
    validate_config(config)

    layer_name = (
        config.get("semantic_layer", {}).get("layer_name")
        or DEFAULT_LAYER_NAME
    )

    logger = configure_logging(project_root, config, run_id)

    runtime = SemanticLayerRuntime(
        run_id=run_id,
        layer_name=layer_name,
        project_root=project_root,
        config_path=config_path,
        start_time_utc=utc_now(),
        logger=logger,
        config=config,
    )

    add_audit_record(
        runtime=runtime,
        step_name="initialize_runtime",
        status=AUDIT_STATUS_SUCCESS,
        message="Runtime initialized successfully.",
    )

    return runtime


###############################################################################
# Audit and Validation Recording
###############################################################################

def add_audit_record(
    runtime: SemanticLayerRuntime,
    step_name: str,
    status: str,
    message: str,
    row_count: Optional[int] = None,
    output_path: Optional[str] = None,
) -> None:
    """
    Add an audit record for the current execution.

    Args:
        runtime:
            Runtime context.

        step_name:
            Name of the execution step.

        status:
            Step status.

        message:
            Human-readable message.

        row_count:
            Optional row count associated with the step.

        output_path:
            Optional output path associated with the step.
    """

    runtime.audit_records.append(
        {
            "run_id": runtime.run_id,
            "layer_name": runtime.layer_name,
            "step_name": step_name,
            "status": status,
            "message": message,
            "row_count": row_count,
            "output_path": output_path,
            "event_timestamp_utc": utc_now().isoformat(),
        }
    )


def add_validation_record(
    runtime: SemanticLayerRuntime,
    dataset_name: str,
    rule_name: str,
    status: str,
    message: str,
    failed_count: Optional[int] = None,
) -> None:
    """
    Add a validation record.

    Args:
        runtime:
            Runtime context.

        dataset_name:
            Dataset being validated.

        rule_name:
            Validation rule name.

        status:
            Validation status.

        message:
            Validation message.

        failed_count:
            Optional count of failed rows.
    """

    runtime.validation_records.append(
        {
            "run_id": runtime.run_id,
            "layer_name": runtime.layer_name,
            "dataset_name": dataset_name,
            "rule_name": rule_name,
            "status": status,
            "message": message,
            "failed_count": failed_count,
            "event_timestamp_utc": utc_now().isoformat(),
        }
    )


def add_dataset_record(
    runtime: SemanticLayerRuntime,
    dataset_name: str,
    dataset_type: str,
    status: str,
    path: Optional[str],
    row_count: int,
    column_count: int,
    message: str,
) -> None:
    """
    Add dataset metadata record.

    Args:
        runtime:
            Runtime context.

        dataset_name:
            Logical dataset name.

        dataset_type:
            Dataset category.

        status:
            Dataset status.

        path:
            Dataset path.

        row_count:
            Number of rows.

        column_count:
            Number of columns.

        message:
            Human-readable message.
    """

    runtime.dataset_records.append(
        {
            "run_id": runtime.run_id,
            "layer_name": runtime.layer_name,
            "dataset_name": dataset_name,
            "dataset_type": dataset_type,
            "status": status,
            "path": path,
            "row_count": row_count,
            "column_count": column_count,
            "message": message,
            "event_timestamp_utc": utc_now().isoformat(),
        }
    )


def add_metric_record(
    runtime: SemanticLayerRuntime,
    metric_name: str,
    metric_group: str,
    description: str,
    source_dataset: str,
    calculation: str,
    grain: str,
    owner: str,
) -> None:
    """
    Add a metric definition record.

    Args:
        runtime:
            Runtime context.

        metric_name:
            Metric name.

        metric_group:
            Metric group.

        description:
            Business definition.

        source_dataset:
            Source dataset.

        calculation:
            Metric calculation expression.

        grain:
            Metric grain.

        owner:
            Business or technical owner.
    """

    runtime.metric_records.append(
        {
            "run_id": runtime.run_id,
            "layer_name": runtime.layer_name,
            "metric_name": metric_name,
            "metric_group": metric_group,
            "description": description,
            "source_dataset": source_dataset,
            "calculation": calculation,
            "grain": grain,
            "owner": owner,
            "event_timestamp_utc": utc_now().isoformat(),
        }
    )


###############################################################################
# File IO Helpers
###############################################################################

def read_dataset(path: Path, file_format: Optional[str] = None) -> pd.DataFrame:
    """
    Read a dataset from disk.

    Args:
        path:
            Dataset path.

        file_format:
            Optional explicit file format. If omitted, inferred from suffix.

    Returns:
        pd.DataFrame:
            Loaded dataframe.

    Raises:
        FileNotFoundError:
            If the path does not exist.

        ValueError:
            If the file format is unsupported.
    """

    if not path.exists():
        raise FileNotFoundError(f"Input dataset not found: {path}")

    resolved_format = file_format or path.suffix.replace(".", "").lower()

    if resolved_format == "parquet":
        return pd.read_parquet(path)

    if resolved_format == "csv":
        return pd.read_csv(path)

    if resolved_format == "json":
        return pd.read_json(path)

    raise ValueError(
        f"Unsupported input file format '{resolved_format}' for path: {path}"
    )


def write_dataset(
    dataframe: pd.DataFrame,
    path: Path,
    file_format: str = DEFAULT_OUTPUT_FORMAT,
) -> None:
    """
    Write a dataframe to disk.

    Args:
        dataframe:
            Dataframe to write.

        path:
            Output path.

        file_format:
            Output format.
    """

    ensure_directory(path.parent)

    if file_format == "parquet":
        dataframe.to_parquet(path, index=False)
        return

    if file_format == "csv":
        dataframe.to_csv(path, index=False)
        return

    if file_format == "json":
        dataframe.to_json(path, orient="records", indent=2)
        return

    raise ValueError(f"Unsupported output file format: {file_format}")


def output_path_with_format(path: Path, output_format: str) -> Path:
    """
    Ensure that an output path has the configured output format suffix.

    Args:
        path:
            Base output path.

        output_format:
            Output format.

    Returns:
        Path:
            Path with correct suffix.
    """

    suffix = f".{output_format}"

    if path.suffix:
        return path.with_suffix(suffix)

    return Path(str(path) + suffix)


###############################################################################
# Path Configuration Helpers
###############################################################################

def get_output_format(runtime: SemanticLayerRuntime) -> str:
    """
    Read configured output format.

    Args:
        runtime:
            Runtime context.

    Returns:
        str:
            Output file format.
    """

    return (
        runtime.config.get("semantic_layer", {})
        .get("output_format", DEFAULT_OUTPUT_FORMAT)
    )


def get_inputs_config(runtime: SemanticLayerRuntime) -> Dict[str, Any]:
    """
    Return configured input datasets.

    Args:
        runtime:
            Runtime context.

    Returns:
        Dict[str, Any]:
            Input configuration dictionary.
    """

    return runtime.config.get("paths", {}).get("inputs", {})


def get_outputs_config(runtime: SemanticLayerRuntime) -> Dict[str, Any]:
    """
    Return configured output paths.

    Args:
        runtime:
            Runtime context.

    Returns:
        Dict[str, Any]:
            Output configuration dictionary.
    """

    return runtime.config.get("paths", {}).get("outputs", {})


def get_metadata_outputs_config(runtime: SemanticLayerRuntime) -> Dict[str, Any]:
    """
    Return configured metadata output paths.

    Args:
        runtime:
            Runtime context.

    Returns:
        Dict[str, Any]:
            Metadata output configuration dictionary.
    """

    return runtime.config.get("paths", {}).get("metadata_outputs", {})


###############################################################################
# Dataset Loading
###############################################################################

def load_feature_store_datasets(runtime: SemanticLayerRuntime) -> Dict[str, pd.DataFrame]:
    """
    Load configured Feature Store datasets.

    The configuration should define input datasets under:
        paths:
          inputs:
            dataset_name:
              path: data/feature_store/example.parquet
              format: parquet
              required: true

    Args:
        runtime:
            Runtime context.

    Returns:
        Dict[str, pd.DataFrame]:
            Mapping of dataset name to dataframe.
    """

    logger = runtime.logger
    inputs_config = get_inputs_config(runtime)

    datasets: Dict[str, pd.DataFrame] = {}

    logger.info("START: Load Feature Store datasets")

    for dataset_name, dataset_config in inputs_config.items():
        if not isinstance(dataset_config, dict):
            add_validation_record(
                runtime=runtime,
                dataset_name=dataset_name,
                rule_name="input_config_shape",
                status=AUDIT_STATUS_FAILED,
                message="Input dataset configuration must be a dictionary.",
            )
            raise ValueError(
                f"Input configuration for '{dataset_name}' must be a dictionary."
            )

        required = bool(dataset_config.get("required", True))
        raw_path = dataset_config.get("path")
        file_format = dataset_config.get("format")

        if not raw_path:
            message = f"No path configured for input dataset: {dataset_name}"

            if required:
                add_validation_record(
                    runtime=runtime,
                    dataset_name=dataset_name,
                    rule_name="input_path_required",
                    status=AUDIT_STATUS_FAILED,
                    message=message,
                )
                raise ValueError(message)

            logger.warning("SKIP optional dataset with no path: %s", dataset_name)
            continue

        dataset_path = normalize_path(runtime.project_root, raw_path)

        try:
            dataframe = read_dataset(dataset_path, file_format)
            datasets[dataset_name] = dataframe

            logger.info(
                "Loaded dataset: %s | Rows: %s | Columns: %s | Path: %s",
                dataset_name,
                len(dataframe),
                len(dataframe.columns),
                dataset_path,
            )

            add_dataset_record(
                runtime=runtime,
                dataset_name=dataset_name,
                dataset_type="feature_store_input",
                status=AUDIT_STATUS_SUCCESS,
                path=str(dataset_path),
                row_count=len(dataframe),
                column_count=len(dataframe.columns),
                message="Feature Store dataset loaded successfully.",
            )

            add_audit_record(
                runtime=runtime,
                step_name=f"load_input_dataset:{dataset_name}",
                status=AUDIT_STATUS_SUCCESS,
                message="Dataset loaded successfully.",
                row_count=len(dataframe),
                output_path=str(dataset_path),
            )

        except Exception as exc:
            message = f"Failed to load input dataset '{dataset_name}': {exc}"

            if required:
                logger.error(message)
                add_audit_record(
                    runtime=runtime,
                    step_name=f"load_input_dataset:{dataset_name}",
                    status=AUDIT_STATUS_FAILED,
                    message=message,
                    output_path=str(dataset_path),
                )
                raise

            logger.warning("Optional dataset skipped: %s | Reason: %s", dataset_name, exc)

            add_audit_record(
                runtime=runtime,
                step_name=f"load_input_dataset:{dataset_name}",
                status=AUDIT_STATUS_SKIPPED,
                message=message,
                output_path=str(dataset_path),
            )

    logger.info("COMPLETE: Load Feature Store datasets | Count: %s", len(datasets))

    return datasets


###############################################################################
# DataFrame Validation Helpers
###############################################################################

def validate_required_columns(
    runtime: SemanticLayerRuntime,
    dataframe: pd.DataFrame,
    dataset_name: str,
    required_columns: Iterable[str],
) -> bool:
    """
    Validate that required columns exist in a dataframe.

    Args:
        runtime:
            Runtime context.

        dataframe:
            Dataframe to validate.

        dataset_name:
            Logical dataset name.

        required_columns:
            Required column names.

    Returns:
        bool:
            True if validation passes, otherwise False.
    """

    required_columns_list = list(required_columns)
    missing_columns = [
        column for column in required_columns_list
        if column not in dataframe.columns
    ]

    if missing_columns:
        add_validation_record(
            runtime=runtime,
            dataset_name=dataset_name,
            rule_name="required_columns",
            status=AUDIT_STATUS_FAILED,
            message=f"Missing required columns: {missing_columns}",
            failed_count=len(missing_columns),
        )
        return False

    add_validation_record(
        runtime=runtime,
        dataset_name=dataset_name,
        rule_name="required_columns",
        status=AUDIT_STATUS_SUCCESS,
        message="All required columns are present.",
        failed_count=0,
    )

    return True


def validate_not_empty(
    runtime: SemanticLayerRuntime,
    dataframe: pd.DataFrame,
    dataset_name: str,
) -> bool:
    """
    Validate that a dataframe is not empty.

    Args:
        runtime:
            Runtime context.

        dataframe:
            Dataframe to validate.

        dataset_name:
            Logical dataset name.

    Returns:
        bool:
            True if not empty, otherwise False.
    """

    if dataframe.empty:
        add_validation_record(
            runtime=runtime,
            dataset_name=dataset_name,
            rule_name="not_empty",
            status=AUDIT_STATUS_FAILED,
            message="Dataset is empty.",
            failed_count=1,
        )
        return False

    add_validation_record(
        runtime=runtime,
        dataset_name=dataset_name,
        rule_name="not_empty",
        status=AUDIT_STATUS_SUCCESS,
        message="Dataset is not empty.",
        failed_count=0,
    )

    return True


def validate_unique_key(
    runtime: SemanticLayerRuntime,
    dataframe: pd.DataFrame,
    dataset_name: str,
    key_columns: Iterable[str],
) -> bool:
    """
    Validate uniqueness of key columns.

    Args:
        runtime:
            Runtime context.

        dataframe:
            Dataframe to validate.

        dataset_name:
            Logical dataset name.

        key_columns:
            Columns that should uniquely identify rows.

    Returns:
        bool:
            True if unique, otherwise False.
    """

    key_columns_list = list(key_columns)

    if not validate_required_columns(runtime, dataframe, dataset_name, key_columns_list):
        return False

    duplicate_count = int(dataframe.duplicated(subset=key_columns_list).sum())

    if duplicate_count > 0:
        add_validation_record(
            runtime=runtime,
            dataset_name=dataset_name,
            rule_name="unique_key",
            status=AUDIT_STATUS_FAILED,
            message=f"Duplicate records found for key columns: {key_columns_list}",
            failed_count=duplicate_count,
        )
        return False

    add_validation_record(
        runtime=runtime,
        dataset_name=dataset_name,
        rule_name="unique_key",
        status=AUDIT_STATUS_SUCCESS,
        message=f"Key columns are unique: {key_columns_list}",
        failed_count=0,
    )

    return True


###############################################################################
# Semantic Column Selection and Renaming
###############################################################################

def select_and_rename_columns(
    dataframe: pd.DataFrame,
    column_mappings: Dict[str, str],
    keep_unmapped: bool = False,
) -> pd.DataFrame:
    """
    Select and rename columns using a semantic mapping.

    Args:
        dataframe:
            Source dataframe.

        column_mappings:
            Mapping of source column name to semantic column name.

        keep_unmapped:
            Whether to retain unmapped source columns.

    Returns:
        pd.DataFrame:
            Transformed dataframe.
    """

    available_mappings = {
        source_column: semantic_column
        for source_column, semantic_column in column_mappings.items()
        if source_column in dataframe.columns
    }

    if keep_unmapped:
        result = dataframe.copy()
        result = result.rename(columns=available_mappings)
        return result

    selected_columns = list(available_mappings.keys())
    result = dataframe[selected_columns].copy()
    result = result.rename(columns=available_mappings)

    return result


def add_standard_semantic_columns(
    dataframe: pd.DataFrame,
    runtime: SemanticLayerRuntime,
    semantic_asset_name: str,
) -> pd.DataFrame:
    """
    Add standard Semantic Layer metadata columns.

    Args:
        dataframe:
            Dataframe to enrich.

        runtime:
            Runtime context.

        semantic_asset_name:
            Semantic asset name.

    Returns:
        pd.DataFrame:
            Enriched dataframe.
    """

    result = dataframe.copy()

    result["semantic_layer_run_id"] = runtime.run_id
    result["semantic_asset_name"] = semantic_asset_name
    result["semantic_layer_built_at_utc"] = utc_now().isoformat()

    return result


###############################################################################
# Semantic Dimensions
###############################################################################

def build_semantic_dimensions(
    runtime: SemanticLayerRuntime,
    datasets: Dict[str, pd.DataFrame],
) -> Dict[str, pd.DataFrame]:
    """
    Build semantic dimensions.

    Configuration example:
        semantic_dimensions:
          enabled: true
          dimensions:
            member_semantic_dimension:
              source_dataset: member_features
              key_columns:
                - member_id
              column_mappings:
                member_id: member_id
                age: member_age
                gender: member_gender
              output_path: data/semantic_layer/dimensions/member_semantic_dimension.parquet

    Args:
        runtime:
            Runtime context.

        datasets:
            Loaded Feature Store datasets.

    Returns:
        Dict[str, pd.DataFrame]:
            Built semantic dimension dataframes.
    """

    logger = runtime.logger
    config = runtime.config.get("semantic_dimensions", {})
    enabled = bool(config.get("enabled", True))

    semantic_dimensions: Dict[str, pd.DataFrame] = {}

    if not enabled:
        logger.info("SKIP: Semantic dimensions disabled by configuration")
        add_audit_record(
            runtime=runtime,
            step_name="build_semantic_dimensions",
            status=AUDIT_STATUS_SKIPPED,
            message="Semantic dimensions disabled by configuration.",
        )
        return semantic_dimensions

    dimensions_config = config.get("dimensions", {})

    logger.info("START: Build semantic dimensions")

    for dimension_name, dimension_config in dimensions_config.items():
        source_dataset_name = dimension_config.get("source_dataset")
        key_columns = dimension_config.get("key_columns", [])
        column_mappings = dimension_config.get("column_mappings", {})
        keep_unmapped = bool(dimension_config.get("keep_unmapped_columns", False))

        if source_dataset_name not in datasets:
            message = (
                f"Source dataset '{source_dataset_name}' not loaded for "
                f"semantic dimension '{dimension_name}'."
            )
            logger.warning(message)
            add_audit_record(
                runtime=runtime,
                step_name=f"build_semantic_dimension:{dimension_name}",
                status=AUDIT_STATUS_SKIPPED,
                message=message,
            )
            continue

        source_df = datasets[source_dataset_name]

        validate_not_empty(runtime, source_df, source_dataset_name)

        if key_columns:
            validate_unique_key(runtime, source_df, source_dataset_name, key_columns)

        if column_mappings:
            semantic_df = select_and_rename_columns(
                dataframe=source_df,
                column_mappings=column_mappings,
                keep_unmapped=keep_unmapped,
            )
        else:
            semantic_df = source_df.copy()

        semantic_df = add_standard_semantic_columns(
            dataframe=semantic_df,
            runtime=runtime,
            semantic_asset_name=dimension_name,
        )

        semantic_dimensions[dimension_name] = semantic_df

        logger.info(
            "Built semantic dimension: %s | Source: %s | Rows: %s | Columns: %s",
            dimension_name,
            source_dataset_name,
            len(semantic_df),
            len(semantic_df.columns),
        )

        add_dataset_record(
            runtime=runtime,
            dataset_name=dimension_name,
            dataset_type="semantic_dimension",
            status=AUDIT_STATUS_SUCCESS,
            path=dimension_config.get("output_path"),
            row_count=len(semantic_df),
            column_count=len(semantic_df.columns),
            message=f"Semantic dimension built from source dataset '{source_dataset_name}'.",
        )

    logger.info(
        "COMPLETE: Build semantic dimensions | Count: %s",
        len(semantic_dimensions),
    )

    add_audit_record(
        runtime=runtime,
        step_name="build_semantic_dimensions",
        status=AUDIT_STATUS_SUCCESS,
        message=f"Semantic dimensions built: {len(semantic_dimensions)}",
    )

    return semantic_dimensions


###############################################################################
# Semantic Metrics
###############################################################################

def calculate_metric(
    dataframe: pd.DataFrame,
    metric_config: Dict[str, Any],
) -> Any:
    """
    Calculate a metric from a dataframe.

    Supported calculation types:
        - count_rows
        - count_distinct
        - sum
        - mean
        - min
        - max
        - median

    Args:
        dataframe:
            Source dataframe.

        metric_config:
            Metric configuration.

    Returns:
        Any:
            Calculated metric value.
    """

    calculation_type = metric_config.get("calculation_type")
    column = metric_config.get("column")

    if calculation_type == "count_rows":
        return int(len(dataframe))

    if calculation_type == "count_distinct":
        if not column:
            raise ValueError("count_distinct metric requires 'column'.")
        return int(dataframe[column].nunique(dropna=True))

    if calculation_type == "sum":
        if not column:
            raise ValueError("sum metric requires 'column'.")
        return dataframe[column].sum()

    if calculation_type == "mean":
        if not column:
            raise ValueError("mean metric requires 'column'.")
        return dataframe[column].mean()

    if calculation_type == "min":
        if not column:
            raise ValueError("min metric requires 'column'.")
        return dataframe[column].min()

    if calculation_type == "max":
        if not column:
            raise ValueError("max metric requires 'column'.")
        return dataframe[column].max()

    if calculation_type == "median":
        if not column:
            raise ValueError("median metric requires 'column'.")
        return dataframe[column].median()

    raise ValueError(f"Unsupported metric calculation_type: {calculation_type}")


def build_semantic_metrics(
    runtime: SemanticLayerRuntime,
    datasets: Dict[str, pd.DataFrame],
) -> Dict[str, pd.DataFrame]:
    """
    Build semantic metrics.

    Configuration example:
        semantic_metrics:
          enabled: true
          metric_groups:
            population_metrics:
              source_dataset: member_features
              grain: platform
              metrics:
                total_members:
                  calculation_type: count_rows
                  description: Total members in the feature store.
                unique_members:
                  calculation_type: count_distinct
                  column: member_id
                  description: Unique members.

    Args:
        runtime:
            Runtime context.

        datasets:
            Loaded Feature Store datasets.

    Returns:
        Dict[str, pd.DataFrame]:
            Metric group dataframes.
    """

    logger = runtime.logger
    config = runtime.config.get("semantic_metrics", {})
    enabled = bool(config.get("enabled", True))

    metric_outputs: Dict[str, pd.DataFrame] = {}

    if not enabled:
        logger.info("SKIP: Semantic metrics disabled by configuration")
        add_audit_record(
            runtime=runtime,
            step_name="build_semantic_metrics",
            status=AUDIT_STATUS_SKIPPED,
            message="Semantic metrics disabled by configuration.",
        )
        return metric_outputs

    metric_groups_config = config.get("metric_groups", {})

    logger.info("START: Build semantic metrics")

    for metric_group_name, metric_group_config in metric_groups_config.items():
        source_dataset_name = metric_group_config.get("source_dataset")
        grain = metric_group_config.get("grain", "platform")
        owner = metric_group_config.get("owner", "MedFabric")
        metrics_config = metric_group_config.get("metrics", {})

        if source_dataset_name not in datasets:
            message = (
                f"Source dataset '{source_dataset_name}' not loaded for "
                f"metric group '{metric_group_name}'."
            )
            logger.warning(message)
            add_audit_record(
                runtime=runtime,
                step_name=f"build_semantic_metric_group:{metric_group_name}",
                status=AUDIT_STATUS_SKIPPED,
                message=message,
            )
            continue

        source_df = datasets[source_dataset_name]
        metric_rows: List[Dict[str, Any]] = []

        for metric_name, metric_config in metrics_config.items():
            try:
                metric_value = calculate_metric(source_df, metric_config)
                description = metric_config.get("description", "")
                calculation_type = metric_config.get("calculation_type", "")
                column = metric_config.get("column", "")

                metric_rows.append(
                    {
                        "metric_group": metric_group_name,
                        "metric_name": metric_name,
                        "metric_value": metric_value,
                        "metric_grain": grain,
                        "source_dataset": source_dataset_name,
                        "calculation_type": calculation_type,
                        "source_column": column,
                        "description": description,
                        "semantic_layer_run_id": runtime.run_id,
                        "semantic_layer_built_at_utc": utc_now().isoformat(),
                    }
                )

                add_metric_record(
                    runtime=runtime,
                    metric_name=metric_name,
                    metric_group=metric_group_name,
                    description=description,
                    source_dataset=source_dataset_name,
                    calculation=f"{calculation_type}({column})",
                    grain=grain,
                    owner=owner,
                )

                add_validation_record(
                    runtime=runtime,
                    dataset_name=metric_group_name,
                    rule_name=f"metric_calculation:{metric_name}",
                    status=AUDIT_STATUS_SUCCESS,
                    message="Metric calculated successfully.",
                    failed_count=0,
                )

            except Exception as exc:
                logger.error(
                    "Failed metric calculation | Metric Group: %s | Metric: %s | Error: %s",
                    metric_group_name,
                    metric_name,
                    exc,
                )

                add_validation_record(
                    runtime=runtime,
                    dataset_name=metric_group_name,
                    rule_name=f"metric_calculation:{metric_name}",
                    status=AUDIT_STATUS_FAILED,
                    message=str(exc),
                    failed_count=1,
                )

                if bool(metric_config.get("required", True)):
                    raise

        metric_df = pd.DataFrame(metric_rows)
        metric_outputs[metric_group_name] = metric_df

        logger.info(
            "Built semantic metric group: %s | Metrics: %s",
            metric_group_name,
            len(metric_df),
        )

        add_dataset_record(
            runtime=runtime,
            dataset_name=metric_group_name,
            dataset_type="semantic_metric_group",
            status=AUDIT_STATUS_SUCCESS,
            path=metric_group_config.get("output_path"),
            row_count=len(metric_df),
            column_count=len(metric_df.columns),
            message=f"Semantic metric group built from source dataset '{source_dataset_name}'.",
        )

    logger.info("COMPLETE: Build semantic metrics | Groups: %s", len(metric_outputs))

    add_audit_record(
        runtime=runtime,
        step_name="build_semantic_metrics",
        status=AUDIT_STATUS_SUCCESS,
        message=f"Semantic metric groups built: {len(metric_outputs)}",
    )

    return metric_outputs


###############################################################################
# Semantic Business Views
###############################################################################

def build_semantic_business_views(
    runtime: SemanticLayerRuntime,
    datasets: Dict[str, pd.DataFrame],
    semantic_dimensions: Dict[str, pd.DataFrame],
    semantic_metrics: Dict[str, pd.DataFrame],
) -> Dict[str, pd.DataFrame]:
    """
    Build semantic business views.

    Business views are configuration-defined analytics-ready datasets. A view can
    currently be produced by:
        - Copying a source dataset
        - Selecting/renaming columns
        - Adding metadata columns

    This function intentionally keeps joins conservative. If a project requires
    complex joins, they should be declared clearly in YAML and implemented with
    explicit validation.

    Args:
        runtime:
            Runtime context.

        datasets:
            Loaded Feature Store datasets.

        semantic_dimensions:
            Built semantic dimensions.

        semantic_metrics:
            Built semantic metric groups.

    Returns:
        Dict[str, pd.DataFrame]:
            Business view dataframes.
    """

    logger = runtime.logger
    config = runtime.config.get("semantic_business_views", {})
    enabled = bool(config.get("enabled", True))

    business_views: Dict[str, pd.DataFrame] = {}

    if not enabled:
        logger.info("SKIP: Semantic business views disabled by configuration")
        add_audit_record(
            runtime=runtime,
            step_name="build_semantic_business_views",
            status=AUDIT_STATUS_SKIPPED,
            message="Semantic business views disabled by configuration.",
        )
        return business_views

    views_config = config.get("views", {})

    available_sources: Dict[str, pd.DataFrame] = {}
    available_sources.update(datasets)
    available_sources.update(semantic_dimensions)
    available_sources.update(semantic_metrics)

    logger.info("START: Build semantic business views")

    for view_name, view_config in views_config.items():
        source_dataset_name = view_config.get("source_dataset")
        column_mappings = view_config.get("column_mappings", {})
        keep_unmapped = bool(view_config.get("keep_unmapped_columns", True))

        if source_dataset_name not in available_sources:
            message = (
                f"Source dataset '{source_dataset_name}' not available for "
                f"business view '{view_name}'."
            )
            logger.warning(message)
            add_audit_record(
                runtime=runtime,
                step_name=f"build_semantic_business_view:{view_name}",
                status=AUDIT_STATUS_SKIPPED,
                message=message,
            )
            continue

        source_df = available_sources[source_dataset_name]

        if column_mappings:
            view_df = select_and_rename_columns(
                dataframe=source_df,
                column_mappings=column_mappings,
                keep_unmapped=keep_unmapped,
            )
        else:
            view_df = source_df.copy()

        filters_config = view_config.get("filters", [])
        view_df = apply_simple_filters(view_df, filters_config)

        view_df = add_standard_semantic_columns(
            dataframe=view_df,
            runtime=runtime,
            semantic_asset_name=view_name,
        )

        business_views[view_name] = view_df

        logger.info(
            "Built semantic business view: %s | Source: %s | Rows: %s | Columns: %s",
            view_name,
            source_dataset_name,
            len(view_df),
            len(view_df.columns),
        )

        add_dataset_record(
            runtime=runtime,
            dataset_name=view_name,
            dataset_type="semantic_business_view",
            status=AUDIT_STATUS_SUCCESS,
            path=view_config.get("output_path"),
            row_count=len(view_df),
            column_count=len(view_df.columns),
            message=f"Semantic business view built from source dataset '{source_dataset_name}'.",
        )

    logger.info(
        "COMPLETE: Build semantic business views | Count: %s",
        len(business_views),
    )

    add_audit_record(
        runtime=runtime,
        step_name="build_semantic_business_views",
        status=AUDIT_STATUS_SUCCESS,
        message=f"Semantic business views built: {len(business_views)}",
    )

    return business_views


def apply_simple_filters(
    dataframe: pd.DataFrame,
    filters_config: List[Dict[str, Any]],
) -> pd.DataFrame:
    """
    Apply simple configuration-defined filters to a dataframe.

    Supported operators:
        - equals
        - not_equals
        - greater_than
        - greater_than_or_equal
        - less_than
        - less_than_or_equal
        - in
        - not_in
        - is_not_null
        - is_null

    Args:
        dataframe:
            Source dataframe.

        filters_config:
            List of filter definitions.

    Returns:
        pd.DataFrame:
            Filtered dataframe.
    """

    result = dataframe.copy()

    for filter_config in filters_config:
        column = filter_config.get("column")
        operator = filter_config.get("operator")
        value = filter_config.get("value")

        if not column or column not in result.columns:
            continue

        if operator == "equals":
            result = result[result[column] == value]
        elif operator == "not_equals":
            result = result[result[column] != value]
        elif operator == "greater_than":
            result = result[result[column] > value]
        elif operator == "greater_than_or_equal":
            result = result[result[column] >= value]
        elif operator == "less_than":
            result = result[result[column] < value]
        elif operator == "less_than_or_equal":
            result = result[result[column] <= value]
        elif operator == "in":
            result = result[result[column].isin(value)]
        elif operator == "not_in":
            result = result[~result[column].isin(value)]
        elif operator == "is_not_null":
            result = result[result[column].notna()]
        elif operator == "is_null":
            result = result[result[column].isna()]

    return result


###############################################################################
# Metadata Catalogs
###############################################################################

def build_semantic_metadata_catalog(
    runtime: SemanticLayerRuntime,
    all_assets: Dict[str, pd.DataFrame],
) -> pd.DataFrame:
    """
    Build semantic metadata catalog.

    Args:
        runtime:
            Runtime context.

        all_assets:
            All semantic assets produced during the run.

    Returns:
        pd.DataFrame:
            Metadata catalog dataframe.
    """

    rows: List[Dict[str, Any]] = []

    for asset_name, dataframe in all_assets.items():
        for column_name in dataframe.columns:
            rows.append(
                {
                    "run_id": runtime.run_id,
                    "layer_name": runtime.layer_name,
                    "semantic_asset_name": asset_name,
                    "column_name": column_name,
                    "data_type": str(dataframe[column_name].dtype),
                    "non_null_count": int(dataframe[column_name].notna().sum()),
                    "null_count": int(dataframe[column_name].isna().sum()),
                    "row_count": int(len(dataframe)),
                    "created_at_utc": utc_now().isoformat(),
                }
            )

    catalog_df = pd.DataFrame(rows)

    add_dataset_record(
        runtime=runtime,
        dataset_name="semantic_metadata_catalog",
        dataset_type="semantic_metadata",
        status=AUDIT_STATUS_SUCCESS,
        path=None,
        row_count=len(catalog_df),
        column_count=len(catalog_df.columns),
        message="Semantic metadata catalog built successfully.",
    )

    return catalog_df


def build_entity_mapping_catalog(runtime: SemanticLayerRuntime) -> pd.DataFrame:
    """
    Build entity mapping catalog from configuration.

    Returns:
        pd.DataFrame:
            Entity mapping catalog.
    """

    config = runtime.config.get("entity_mappings", {})
    mappings = config.get("mappings", {})

    rows: List[Dict[str, Any]] = []

    for entity_name, entity_config in mappings.items():
        source_dataset = entity_config.get("source_dataset", "")
        business_key = entity_config.get("business_key", "")
        semantic_key = entity_config.get("semantic_key", "")
        description = entity_config.get("description", "")

        rows.append(
            {
                "run_id": runtime.run_id,
                "layer_name": runtime.layer_name,
                "entity_name": entity_name,
                "source_dataset": source_dataset,
                "business_key": business_key,
                "semantic_key": semantic_key,
                "description": description,
                "created_at_utc": utc_now().isoformat(),
            }
        )

    return pd.DataFrame(rows)


def build_configuration_catalog(runtime: SemanticLayerRuntime) -> pd.DataFrame:
    """
    Build flattened configuration catalog.

    Args:
        runtime:
            Runtime context.

    Returns:
        pd.DataFrame:
            Configuration catalog dataframe.
    """

    flattened = flatten_dict(runtime.config)

    rows = [
        {
            "run_id": runtime.run_id,
            "layer_name": runtime.layer_name,
            "config_key": key,
            "config_value": safe_string(value),
            "created_at_utc": utc_now().isoformat(),
        }
        for key, value in flattened.items()
    ]

    return pd.DataFrame(rows)


###############################################################################
# Output Writing
###############################################################################

def write_configured_outputs(
    runtime: SemanticLayerRuntime,
    semantic_dimensions: Dict[str, pd.DataFrame],
    semantic_metrics: Dict[str, pd.DataFrame],
    semantic_business_views: Dict[str, pd.DataFrame],
    metadata_catalogs: Dict[str, pd.DataFrame],
) -> None:
    """
    Write all configured semantic outputs.

    Args:
        runtime:
            Runtime context.

        semantic_dimensions:
            Built semantic dimensions.

        semantic_metrics:
            Built semantic metric groups.

        semantic_business_views:
            Built semantic business views.

        metadata_catalogs:
            Built metadata catalog dataframes.
    """

    logger = runtime.logger
    output_format = get_output_format(runtime)

    logger.info("START: Write semantic layer outputs")

    write_asset_group_outputs(
        runtime=runtime,
        asset_group_name="semantic_dimensions",
        assets=semantic_dimensions,
        config_section="semantic_dimensions",
        child_section="dimensions",
        output_format=output_format,
    )

    write_asset_group_outputs(
        runtime=runtime,
        asset_group_name="semantic_metrics",
        assets=semantic_metrics,
        config_section="semantic_metrics",
        child_section="metric_groups",
        output_format=output_format,
    )

    write_asset_group_outputs(
        runtime=runtime,
        asset_group_name="semantic_business_views",
        assets=semantic_business_views,
        config_section="semantic_business_views",
        child_section="views",
        output_format=output_format,
    )

    write_metadata_outputs(
        runtime=runtime,
        metadata_catalogs=metadata_catalogs,
        output_format=output_format,
    )

    logger.info("COMPLETE: Write semantic layer outputs")

    add_audit_record(
        runtime=runtime,
        step_name="write_configured_outputs",
        status=AUDIT_STATUS_SUCCESS,
        message="Semantic layer outputs written successfully.",
    )


def write_asset_group_outputs(
    runtime: SemanticLayerRuntime,
    asset_group_name: str,
    assets: Dict[str, pd.DataFrame],
    config_section: str,
    child_section: str,
    output_format: str,
) -> None:
    """
    Write one group of semantic assets.

    Args:
        runtime:
            Runtime context.

        asset_group_name:
            Asset group name for logging.

        assets:
            Asset dataframe mapping.

        config_section:
            Parent config section.

        child_section:
            Child config section.

        output_format:
            Output file format.
    """

    logger = runtime.logger
    section_config = runtime.config.get(config_section, {})
    child_config = section_config.get(child_section, {})

    default_output_dir_raw = section_config.get(
        "default_output_dir",
        f"data/semantic_layer/{asset_group_name}",
    )

    default_output_dir = normalize_path(runtime.project_root, default_output_dir_raw)
    ensure_directory(default_output_dir)

    for asset_name, dataframe in assets.items():
        asset_config = child_config.get(asset_name, {})
        output_path_raw = asset_config.get(
            "output_path",
            str(default_output_dir / asset_name),
        )

        output_path = normalize_path(runtime.project_root, output_path_raw)
        output_path = output_path_with_format(output_path, output_format)

        write_dataset(dataframe, output_path, output_format)

        logger.info(
            "Wrote %s asset: %s | Rows: %s | Path: %s",
            asset_group_name,
            asset_name,
            len(dataframe),
            output_path,
        )

        add_audit_record(
            runtime=runtime,
            step_name=f"write_output:{asset_name}",
            status=AUDIT_STATUS_SUCCESS,
            message=f"Output written for {asset_group_name}.",
            row_count=len(dataframe),
            output_path=str(output_path),
        )


def write_metadata_outputs(
    runtime: SemanticLayerRuntime,
    metadata_catalogs: Dict[str, pd.DataFrame],
    output_format: str,
) -> None:
    """
    Write metadata outputs.

    Args:
        runtime:
            Runtime context.

        metadata_catalogs:
            Metadata dataframe mapping.

        output_format:
            Output format.
    """

    logger = runtime.logger
    metadata_outputs_config = get_metadata_outputs_config(runtime)

    default_metadata_dir_raw = metadata_outputs_config.get(
        "default_output_dir",
        "data/semantic_layer/metadata",
    )

    default_metadata_dir = normalize_path(runtime.project_root, default_metadata_dir_raw)
    ensure_directory(default_metadata_dir)

    for metadata_name, dataframe in metadata_catalogs.items():
        output_path_raw = metadata_outputs_config.get(
            metadata_name,
            str(default_metadata_dir / metadata_name),
        )

        output_path = normalize_path(runtime.project_root, output_path_raw)
        output_path = output_path_with_format(output_path, output_format)

        write_dataset(dataframe, output_path, output_format)

        logger.info(
            "Wrote metadata output: %s | Rows: %s | Path: %s",
            metadata_name,
            len(dataframe),
            output_path,
        )

        add_audit_record(
            runtime=runtime,
            step_name=f"write_metadata:{metadata_name}",
            status=AUDIT_STATUS_SUCCESS,
            message="Metadata output written successfully.",
            row_count=len(dataframe),
            output_path=str(output_path),
        )


###############################################################################
# Audit Output Writing
###############################################################################

def write_audit_outputs(runtime: SemanticLayerRuntime) -> None:
    """
    Write audit, validation, dataset, and metric records.

    Args:
        runtime:
            Runtime context.
    """

    logger = runtime.logger
    output_format = get_output_format(runtime)

    paths_config = runtime.config.get("paths", {})
    audit_config = paths_config.get("audit_outputs", {})

    default_audit_dir_raw = audit_config.get(
        "default_output_dir",
        "data/semantic_layer/audit",
    )

    default_audit_dir = normalize_path(runtime.project_root, default_audit_dir_raw)
    ensure_directory(default_audit_dir)

    audit_frames = {
        "semantic_layer_audit_records": pd.DataFrame(runtime.audit_records),
        "semantic_layer_validation_results": pd.DataFrame(runtime.validation_records),
        "semantic_layer_dataset_inventory": pd.DataFrame(runtime.dataset_records),
        "semantic_layer_metric_definitions": pd.DataFrame(runtime.metric_records),
    }

    for name, dataframe in audit_frames.items():
        output_path_raw = audit_config.get(name, str(default_audit_dir / name))
        output_path = normalize_path(runtime.project_root, output_path_raw)
        output_path = output_path_with_format(output_path, output_format)

        write_dataset(dataframe, output_path, output_format)

        logger.info(
            "Wrote audit output: %s | Rows: %s | Path: %s",
            name,
            len(dataframe),
            output_path,
        )


###############################################################################
# Execution Summary
###############################################################################

def build_execution_summary(
    runtime: SemanticLayerRuntime,
    semantic_dimensions: Dict[str, pd.DataFrame],
    semantic_metrics: Dict[str, pd.DataFrame],
    semantic_business_views: Dict[str, pd.DataFrame],
) -> pd.DataFrame:
    """
    Build execution summary dataframe.

    Args:
        runtime:
            Runtime context.

        semantic_dimensions:
            Semantic dimensions.

        semantic_metrics:
            Semantic metrics.

        semantic_business_views:
            Semantic business views.

    Returns:
        pd.DataFrame:
            One-row execution summary.
    """

    end_time = utc_now()
    duration_seconds = (end_time - runtime.start_time_utc).total_seconds()

    failed_validations = [
        record for record in runtime.validation_records
        if record.get("status") == AUDIT_STATUS_FAILED
    ]

    summary = {
        "run_id": runtime.run_id,
        "layer_name": runtime.layer_name,
        "config_path": str(runtime.config_path),
        "start_time_utc": runtime.start_time_utc.isoformat(),
        "end_time_utc": end_time.isoformat(),
        "duration_seconds": duration_seconds,
        "semantic_dimension_count": len(semantic_dimensions),
        "semantic_metric_group_count": len(semantic_metrics),
        "semantic_business_view_count": len(semantic_business_views),
        "audit_record_count": len(runtime.audit_records),
        "validation_record_count": len(runtime.validation_records),
        "failed_validation_count": len(failed_validations),
        "dataset_record_count": len(runtime.dataset_records),
        "metric_definition_count": len(runtime.metric_records),
        "status": (
            AUDIT_STATUS_SUCCESS
            if len(failed_validations) == 0
            else AUDIT_STATUS_WARNING
        ),
    }

    return pd.DataFrame([summary])


def write_execution_summary(
    runtime: SemanticLayerRuntime,
    summary_df: pd.DataFrame,
) -> None:
    """
    Write execution summary.

    Args:
        runtime:
            Runtime context.

        summary_df:
            Execution summary dataframe.
    """

    logger = runtime.logger
    output_format = get_output_format(runtime)

    paths_config = runtime.config.get("paths", {})
    audit_config = paths_config.get("audit_outputs", {})

    default_audit_dir_raw = audit_config.get(
        "default_output_dir",
        "data/semantic_layer/audit",
    )

    default_audit_dir = normalize_path(runtime.project_root, default_audit_dir_raw)
    ensure_directory(default_audit_dir)

    output_path_raw = audit_config.get(
        "semantic_layer_execution_summary",
        str(default_audit_dir / "semantic_layer_execution_summary"),
    )

    output_path = normalize_path(runtime.project_root, output_path_raw)
    output_path = output_path_with_format(output_path, output_format)

    write_dataset(summary_df, output_path, output_format)

    logger.info(
        "Wrote execution summary | Rows: %s | Path: %s",
        len(summary_df),
        output_path,
    )


###############################################################################
# Main Orchestration
###############################################################################

def build_semantic_layer(config_path: str = DEFAULT_CONFIG_PATH) -> DatasetResult:
    """
    Build the complete MedFabric Semantic Layer.

    Args:
        config_path:
            Path to semantic layer YAML configuration.

    Returns:
        DatasetResult:
            Final execution result.
    """

    runtime: Optional[SemanticLayerRuntime] = None

    try:
        runtime = initialize_runtime(config_path)
        logger = runtime.logger

        logger.info("Semantic Layer configuration path: %s", runtime.config_path)

        datasets = load_feature_store_datasets(runtime)

        semantic_dimensions = build_semantic_dimensions(runtime, datasets)

        semantic_metrics = build_semantic_metrics(runtime, datasets)

        semantic_business_views = build_semantic_business_views(
            runtime=runtime,
            datasets=datasets,
            semantic_dimensions=semantic_dimensions,
            semantic_metrics=semantic_metrics,
        )

        all_semantic_assets: Dict[str, pd.DataFrame] = {}
        all_semantic_assets.update(semantic_dimensions)
        all_semantic_assets.update(semantic_metrics)
        all_semantic_assets.update(semantic_business_views)

        metadata_catalogs = {
            "semantic_metadata_catalog": build_semantic_metadata_catalog(
                runtime=runtime,
                all_assets=all_semantic_assets,
            ),
            "semantic_entity_mapping_catalog": build_entity_mapping_catalog(runtime),
            "semantic_configuration_catalog": build_configuration_catalog(runtime),
        }

        write_configured_outputs(
            runtime=runtime,
            semantic_dimensions=semantic_dimensions,
            semantic_metrics=semantic_metrics,
            semantic_business_views=semantic_business_views,
            metadata_catalogs=metadata_catalogs,
        )

        summary_df = build_execution_summary(
            runtime=runtime,
            semantic_dimensions=semantic_dimensions,
            semantic_metrics=semantic_metrics,
            semantic_business_views=semantic_business_views,
        )

        add_audit_record(
            runtime=runtime,
            step_name="build_semantic_layer",
            status=AUDIT_STATUS_SUCCESS,
            message="Semantic Layer completed successfully.",
        )

        write_audit_outputs(runtime)
        write_execution_summary(runtime, summary_df)

        logger.info("=" * 80)
        logger.info("MedFabric Semantic Layer completed successfully")
        logger.info(
            "Dimensions: %s | Metric Groups: %s | Business Views: %s",
            len(semantic_dimensions),
            len(semantic_metrics),
            len(semantic_business_views),
        )
        logger.info("=" * 80)

        return DatasetResult(
            name="semantic_layer",
            status=AUDIT_STATUS_SUCCESS,
            row_count=len(summary_df),
            column_count=len(summary_df.columns),
            message="MedFabric Semantic Layer completed successfully.",
        )

    except Exception as exc:
        if runtime is not None:
            runtime.logger.error("=" * 80)
            runtime.logger.error("MedFabric Semantic Layer failed")
            runtime.logger.error("Error: %s", exc)
            runtime.logger.error("Traceback:\n%s", traceback.format_exc())
            runtime.logger.error("=" * 80)

            add_audit_record(
                runtime=runtime,
                step_name="build_semantic_layer",
                status=AUDIT_STATUS_FAILED,
                message=str(exc),
            )

            try:
                write_audit_outputs(runtime)
            except Exception as audit_exc:
                runtime.logger.error("Failed to write audit outputs: %s", audit_exc)

        return DatasetResult(
            name="semantic_layer",
            status=AUDIT_STATUS_FAILED,
            message=str(exc),
        )


###############################################################################
# CLI Entry Point
###############################################################################

def main() -> None:
    """
    Command-line entry point.

    This function allows the Semantic Layer to be executed with:

        python -m src.semantic_layer.build_semantic_layer

    Optional environment variable:
        MEDFABRIC_SEMANTIC_LAYER_CONFIG

    Example:
        MEDFABRIC_SEMANTIC_LAYER_CONFIG=config/semantic_layer/semantic_layer.yaml \
        python -m src.semantic_layer.build_semantic_layer
    """

    config_path = os.environ.get(
        "MEDFABRIC_SEMANTIC_LAYER_CONFIG",
        DEFAULT_CONFIG_PATH,
    )

    result = build_semantic_layer(config_path=config_path)

    if result.status == AUDIT_STATUS_SUCCESS:
        print(result.message)
        return

    print(f"MedFabric Semantic Layer failed: {result.message}")
    sys.exit(1)


if __name__ == "__main__":
    main()